version: "3.8"

services:

  database:
    container_name: database
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
    - database:/data/
    ports:
    - "5432:5432"
    networks:
      - sql


  vault:
    image: library/vault:1.13.3
    container_name: vault
    cap_add:
        - IPC_LOCK
    volumes:
    - ./vault/config:/vault/config
    - ./vault/policies:/vault/policies
    command: >
          sh -c "vault server -config=/vault/config/vault-config.json"
    ports:
    - "8200:8200/tcp"
    networks:
      - vault


  authorization_app:
    container_name: authorization
    build:
      ./
    command: uvicorn main:authorization --host 0.0.0.0 --port 7000
    ports:
      - "7000:7000"
    networks:
      - sql
      - vault
    develop:
      watch:
        - action: sync
          path: src/authorization
          target: src/authorization
          ignore:
            - .git
            - .github
            - .idea
            - .venv
            - .gitignore
            - README.md
        - action: sync
          path: /src/authorization
          target: src/authorization
        - action: sync
          path: /src/registration
          target: src/registration
        - action: sync
          path: /src/settings
          target: src/settings
        - action: sync
          path:  /src/vault
          target: src/vault
        - action: sync
          path: main.py
          target: main.py
        - action: rebuild
          path: pyproject.toml


networks:
    sql:
      external: true
    vault:

volumes:
  database: