version: "3.8"

services:

  vault:
    image: library/vault:1.13.3
    container_name: vault
    cap_add:
        - IPC_LOCK
    volumes:
    - ./vault/config:/vault/config
    - ./vault/policies:/vault/policies
    command: >
          sh -c "vault server -config=/vault/config/vault-config.json"
    ports:
    - "8200:8200/tcp"
    networks:
      - vault

  authorization_app:
    container_name: authorization
    build:
      ./
    command: uvicorn main:authorization --host 0.0.0.0 --port 7000
    ports:
      - "7000:7000"
    networks:
      - sql
      - vault
      - nginx
      - rabbit
    develop:
      watch:
        - action: sync
          path: src/
          target: src/

        - action: sync
          path: src/authorization
          target: src/authorization

        - action: sync
          path: src/broker
          target: src/broker

        - action: sync
          path: src/password
          target: src/password

        - action: sync
          path: src/registration
          target: src/registration

        - action: sync
          path: src/settings
          target: src/settings

        - action: sync
          path: src/vault
          target: src/vault

        - action: sync
          path: vault/
          target: vault/

        - action: sync
          path: migrations/
          target: migrations/

        - action: sync
          path: ./
          target: ./
          ignore:
            - src/
            - migrations/
            - vault/
            - .idea
            - .venv
            - .gitignore
            - README.md
            - docker-compose.yml
            - Dockerfile
            - poetry.lock
            - pyproject.toml

        - action: rebuild
          path: pyproject.toml

networks:
    sql:
      external: true
    vault:
      external: true
    nginx:
      external: true
    rabbit:
      external: true
