version: "3.8"

services:

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_NAME}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    volumes:
    - database:/data/
    ports:
    - "5432:5432"
    networks:
      - sql

  vault:
    image: library/vault:1.13.3
    container_name: vault
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
        - IPC_LOCK
    volumes:
    - ./vault/config:/vault/config
    - ./vault/policies:/vault/policies
    command: >
          sh -c "vault server -config=/vault/config/vault-config.json"
    ports:
    - "8200:8200/tcp"
    networks:
      - vault


  authorization_app:
    container_name: authorization
    build:
      ./
    command: uvicorn main:authorization --host 0.0.0.0 --port 7000
    ports:
      - "7000:7000"
    networks:
      - sql
      - vault

networks:
    sql:
      external: true
    vault:

volumes:
  database: