version: "3.8"

services:

  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - database:/var/lib/database/
    ports:
    - "5432:5432"

  authorization_app:
    container_name: authorization
    build:
      ./
    links:
      - database
    command: uvicorn main:authorization --host 0.0.0.0 --port 7000
    ports:
      - "7000:7000"


volumes:
  database: